////////////////////////////////////////////////////////////////////////
//
// AltovaXMLAPI.h
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef ALTOVA_XML_API_H_INCLUDED
#define ALTOVA_XML_API_H_INCLUDED


#define ALTOVAXML_DECLSPECIFIER


#endif // ALTOVA_XML_API_H_INCLUDED
