#ifndef _ALTOVA_INCLUDED_CMSD_ALTOVA__ALTOVA_CCMSD
#define _ALTOVA_INCLUDED_CMSD_ALTOVA__ALTOVA_CCMSD



namespace CMSD
{

class CCMSD : public TypeBase
{
public:
	CMSD_EXPORT CCMSD(MSXML2::IXMLDOMNodePtr const& init);
	CMSD_EXPORT CCMSD(CCMSD const& init);
	void operator=(CCMSD const& other) { m_node = other.m_node; }
	static altova::meta::ComplexType StaticInfo() { return altova::meta::ComplexType(types + _altova_ti_altova_CCMSD); }
	MemberElement<CAbstractEntityReference, _altova_mi_altova_CCMSD_altova_AbstractEntityReference> AbstractEntityReference;
	struct AbstractEntityReference { typedef Iterator<CAbstractEntityReference> iterator; };
	MemberElement<CAddress, _altova_mi_altova_CCMSD_altova_Address> Address;
	struct Address { typedef Iterator<CAddress> iterator; };
	MemberElement<CAreaType, _altova_mi_altova_CCMSD_altova_AreaType> AreaType;
	struct AreaType { typedef Iterator<CAreaType> iterator; };
	MemberElement<CAreaUnitType, _altova_mi_altova_CCMSD_altova_AreaUnit> AreaUnit;
	struct AreaUnit { typedef Iterator<CAreaUnitType> iterator; };
	MemberElement<CArrayOfTransformationOperation, _altova_mi_altova_CCMSD_altova_ArrayOfTransformationOperation> ArrayOfTransformationOperation;
	struct ArrayOfTransformationOperation { typedef Iterator<CArrayOfTransformationOperation> iterator; };
	MemberElement<CAvailabilityException, _altova_mi_altova_CCMSD_altova_AvailabilityException> AvailabilityException;
	struct AvailabilityException { typedef Iterator<CAvailabilityException> iterator; };
	MemberElement<CBaseLocationType, _altova_mi_altova_CCMSD_altova_BaseLocation> BaseLocation;
	struct BaseLocation { typedef Iterator<CBaseLocationType> iterator; };
	MemberElement<CBasicShape, _altova_mi_altova_CCMSD_altova_BasicShape> BasicShape;
	struct BasicShape { typedef Iterator<CBasicShape> iterator; };
	MemberElement<CBasicShapeTypeType, _altova_mi_altova_CCMSD_altova_BasicShapeType> BasicShapeType;
	struct BasicShapeType { typedef Iterator<CBasicShapeTypeType> iterator; };
	MemberElement<CBillOfMaterials, _altova_mi_altova_CCMSD_altova_BillOfMaterials> BillOfMaterials;
	struct BillOfMaterials { typedef Iterator<CBillOfMaterials> iterator; };
	MemberElement<CBillOfMaterialsComponent, _altova_mi_altova_CCMSD_altova_BillOfMaterialsComponent> BillOfMaterialsComponent;
	struct BillOfMaterialsComponent { typedef Iterator<CBillOfMaterialsComponent> iterator; };
	MemberElement<CBillOfMaterialsComponentReference, _altova_mi_altova_CCMSD_altova_BillOfMaterialsComponentReference> BillOfMaterialsComponentReference;
	struct BillOfMaterialsComponentReference { typedef Iterator<CBillOfMaterialsComponentReference> iterator; };
	MemberElement<CBillOfMaterialsReference, _altova_mi_altova_CCMSD_altova_BillOfMaterialsReference> BillOfMaterialsReference;
	struct BillOfMaterialsReference { typedef Iterator<CBillOfMaterialsReference> iterator; };
	MemberElement<CBoundaryDefinition, _altova_mi_altova_CCMSD_altova_BoundaryDefinition> BoundaryDefinition;
	struct BoundaryDefinition { typedef Iterator<CBoundaryDefinition> iterator; };
	MemberElement<CBreak, _altova_mi_altova_CCMSD_altova_Break2> Break2;
	struct Break2 { typedef Iterator<CBreak> iterator; };
	MemberElement<CCMSDDecimalType, _altova_mi_altova_CCMSD_altova_CMSDDecimal> CMSDDecimal;
	struct CMSDDecimal { typedef Iterator<CCMSDDecimalType> iterator; };
	MemberElement<CCMSDDocument, _altova_mi_altova_CCMSD_altova_CMSDDocument> CMSDDocument;
	struct CMSDDocument { typedef Iterator<CCMSDDocument> iterator; };
	MemberElement<CCMSDDocumentReference, _altova_mi_altova_CCMSD_altova_CMSDDocumentReference> CMSDDocumentReference;
	struct CMSDDocumentReference { typedef Iterator<CCMSDDocumentReference> iterator; };
	MemberElement<CCMSDDocumentTest, _altova_mi_altova_CCMSD_altova_CMSDDocumentTest> CMSDDocumentTest;
	struct CMSDDocumentTest { typedef Iterator<CCMSDDocumentTest> iterator; };
	MemberElement<CCalendar, _altova_mi_altova_CCMSD_altova_Calendar> Calendar;
	struct Calendar { typedef Iterator<CCalendar> iterator; };
	MemberElement<CCalendarReference, _altova_mi_altova_CCMSD_altova_CalendarReference> CalendarReference;
	struct CalendarReference { typedef Iterator<CCalendarReference> iterator; };
	MemberElement<CCardinalitySpecificationType, _altova_mi_altova_CCMSD_altova_CardinalitySpecification> CardinalitySpecification;
	struct CardinalitySpecification { typedef Iterator<CCardinalitySpecificationType> iterator; };
	MemberElement<CColorHighlight, _altova_mi_altova_CCMSD_altova_ColorHighlight> ColorHighlight;
	struct ColorHighlight { typedef Iterator<CColorHighlight> iterator; };
	MemberElement<CCommunicationMethod, _altova_mi_altova_CCMSD_altova_CommunicationMethod> CommunicationMethod;
	struct CommunicationMethod { typedef Iterator<CCommunicationMethod> iterator; };
	MemberElement<CCommunicationMethodGroup, _altova_mi_altova_CCMSD_altova_CommunicationMethodGroup> CommunicationMethodGroup;
	struct CommunicationMethodGroup { typedef Iterator<CCommunicationMethodGroup> iterator; };
	MemberElement<CConnection, _altova_mi_altova_CCMSD_altova_Connection> Connection;
	struct Connection { typedef Iterator<CConnection> iterator; };
	MemberElement<CConnectionTypeType, _altova_mi_altova_CCMSD_altova_ConnectionType> ConnectionType;
	struct ConnectionType { typedef Iterator<CConnectionTypeType> iterator; };
	MemberElement<CContactInformation, _altova_mi_altova_CCMSD_altova_ContactInformation> ContactInformation;
	struct ContactInformation { typedef Iterator<CContactInformation> iterator; };
	MemberElement<CContactParty, _altova_mi_altova_CCMSD_altova_ContactParty> ContactParty;
	struct ContactParty { typedef Iterator<CContactParty> iterator; };
	MemberElement<CCoordinate2D, _altova_mi_altova_CCMSD_altova_Coordinate2D> Coordinate2D;
	struct Coordinate2D { typedef Iterator<CCoordinate2D> iterator; };
	MemberElement<CCoordinate3D, _altova_mi_altova_CCMSD_altova_Coordinate3D> Coordinate3D;
	struct Coordinate3D { typedef Iterator<CCoordinate3D> iterator; };
	MemberElement<CCoordinateSystemType, _altova_mi_altova_CCMSD_altova_CoordinateSystem> CoordinateSystem;
	struct CoordinateSystem { typedef Iterator<CCoordinateSystemType> iterator; };
	MemberElement<CCostAllocationData, _altova_mi_altova_CCMSD_altova_CostAllocationData> CostAllocationData;
	struct CostAllocationData { typedef Iterator<CCostAllocationData> iterator; };
	MemberElement<CCostCategoryType, _altova_mi_altova_CCMSD_altova_CostCategory> CostCategory;
	struct CostCategory { typedef Iterator<CCostCategoryType> iterator; };
	MemberElement<CCostTypeType, _altova_mi_altova_CCMSD_altova_CostType> CostType;
	struct CostType { typedef Iterator<CCostTypeType> iterator; };
	MemberElement<CCurrencyType, _altova_mi_altova_CCMSD_altova_CurrencyType> CurrencyType;
	struct CurrencyType { typedef Iterator<CCurrencyType> iterator; };
	MemberElement<CDataSectionType, _altova_mi_altova_CCMSD_altova_DataSection> DataSection;
	struct DataSection { typedef Iterator<CDataSectionType> iterator; };
	MemberElement<CDateType, _altova_mi_altova_CCMSD_altova_Date> Date;
	struct Date { typedef Iterator<CDateType> iterator; };
	MemberElement<CDayType, _altova_mi_altova_CCMSD_altova_Day> Day;
	struct Day { typedef Iterator<CDayType> iterator; };
	MemberElement<CDistribution, _altova_mi_altova_CCMSD_altova_Distribution> Distribution;
	struct Distribution { typedef Iterator<CDistribution> iterator; };
	MemberElement<CDistributionDefinition, _altova_mi_altova_CCMSD_altova_DistributionDefinition> DistributionDefinition;
	struct DistributionDefinition { typedef Iterator<CDistributionDefinition> iterator; };
	MemberElement<CDistributionDefinitionReference, _altova_mi_altova_CCMSD_altova_DistributionDefinitionReference> DistributionDefinitionReference;
	struct DistributionDefinitionReference { typedef Iterator<CDistributionDefinitionReference> iterator; };
	MemberElement<CDistributionParameter, _altova_mi_altova_CCMSD_altova_DistributionParameter> DistributionParameter;
	struct DistributionParameter { typedef Iterator<CDistributionParameter> iterator; };
	MemberElement<CDuration, _altova_mi_altova_CCMSD_altova_Duration> Duration;
	struct Duration { typedef Iterator<CDuration> iterator; };
	MemberElement<CElapsedTimeType, _altova_mi_altova_CCMSD_altova_ElapsedTimeType> ElapsedTimeType;
	struct ElapsedTimeType { typedef Iterator<CElapsedTimeType> iterator; };
	MemberElement<CEmail, _altova_mi_altova_CCMSD_altova_Email> Email;
	struct Email { typedef Iterator<CEmail> iterator; };
	MemberElement<CEntity, _altova_mi_altova_CCMSD_altova_Entity> Entity;
	struct Entity { typedef Iterator<CEntity> iterator; };
	MemberElement<CEvent, _altova_mi_altova_CCMSD_altova_Event> Event;
	struct Event { typedef Iterator<CEvent> iterator; };
	MemberElement<CGraphicDescription, _altova_mi_altova_CCMSD_altova_GraphicDescription> GraphicDescription;
	struct GraphicDescription { typedef Iterator<CGraphicDescription> iterator; };
	MemberElement<CGraphicDescriptionTypeType, _altova_mi_altova_CCMSD_altova_GraphicDescriptionType> GraphicDescriptionType;
	struct GraphicDescriptionType { typedef Iterator<CGraphicDescriptionTypeType> iterator; };
	MemberElement<CGrossDimensions, _altova_mi_altova_CCMSD_altova_GrossDimensions> GrossDimensions;
	struct GrossDimensions { typedef Iterator<CGrossDimensions> iterator; };
	MemberElement<CHeaderSection, _altova_mi_altova_CCMSD_altova_HeaderSection> HeaderSection;
	struct HeaderSection { typedef Iterator<CHeaderSection> iterator; };
	MemberElement<CHoliday, _altova_mi_altova_CCMSD_altova_Holiday> Holiday;
	struct Holiday { typedef Iterator<CHoliday> iterator; };
	MemberElement<CIdentifiableEntity, _altova_mi_altova_CCMSD_altova_IdentifiableEntity> IdentifiableEntity;
	struct IdentifiableEntity { typedef Iterator<CIdentifiableEntity> iterator; };
	MemberElement<CIdentifierType, _altova_mi_altova_CCMSD_altova_Identifier> Identifier;
	struct Identifier { typedef Iterator<CIdentifierType> iterator; };
	MemberElement<CImageResolution, _altova_mi_altova_CCMSD_altova_ImageResolution> ImageResolution;
	struct ImageResolution { typedef Iterator<CImageResolution> iterator; };
	MemberElement<CIntegerType, _altova_mi_altova_CCMSD_altova_Integer> Integer;
	struct Integer { typedef Iterator<CIntegerType> iterator; };
	MemberElement<CInventoryItem, _altova_mi_altova_CCMSD_altova_InventoryItem> InventoryItem;
	struct InventoryItem { typedef Iterator<CInventoryItem> iterator; };
	MemberElement<CInventoryItemClass, _altova_mi_altova_CCMSD_altova_InventoryItemClass> InventoryItemClass;
	struct InventoryItemClass { typedef Iterator<CInventoryItemClass> iterator; };
	MemberElement<CInventoryItemClassReference, _altova_mi_altova_CCMSD_altova_InventoryItemClassReference> InventoryItemClassReference;
	struct InventoryItemClassReference { typedef Iterator<CInventoryItemClassReference> iterator; };
	MemberElement<CInventoryItemReference, _altova_mi_altova_CCMSD_altova_InventoryItemReference> InventoryItemReference;
	struct InventoryItemReference { typedef Iterator<CInventoryItemReference> iterator; };
	MemberElement<CInventoryItemTypeType, _altova_mi_altova_CCMSD_altova_InventoryItemType> InventoryItemType;
	struct InventoryItemType { typedef Iterator<CInventoryItemTypeType> iterator; };
	MemberElement<CItemPackaging, _altova_mi_altova_CCMSD_altova_ItemPackaging> ItemPackaging;
	struct ItemPackaging { typedef Iterator<CItemPackaging> iterator; };
	MemberElement<CJob, _altova_mi_altova_CCMSD_altova_Job> Job;
	struct Job { typedef Iterator<CJob> iterator; };
	MemberElement<CJobConstraint, _altova_mi_altova_CCMSD_altova_JobConstraint> JobConstraint;
	struct JobConstraint { typedef Iterator<CJobConstraint> iterator; };
	MemberElement<CJobEffortDescription, _altova_mi_altova_CCMSD_altova_JobEffortDescription> JobEffortDescription;
	struct JobEffortDescription { typedef Iterator<CJobEffortDescription> iterator; };
	MemberElement<CJobReference, _altova_mi_altova_CCMSD_altova_JobReference> JobReference;
	struct JobReference { typedef Iterator<CJobReference> iterator; };
	MemberElement<CJobStatusType, _altova_mi_altova_CCMSD_altova_JobStatus> JobStatus;
	struct JobStatus { typedef Iterator<CJobStatusType> iterator; };
	MemberElement<CLayout, _altova_mi_altova_CCMSD_altova_Layout> Layout;
	struct Layout { typedef Iterator<CLayout> iterator; };
	MemberElement<CLayoutElement, _altova_mi_altova_CCMSD_altova_LayoutElement> LayoutElement;
	struct LayoutElement { typedef Iterator<CLayoutElement> iterator; };
	MemberElement<CLayoutElementReference, _altova_mi_altova_CCMSD_altova_LayoutElementReference> LayoutElementReference;
	struct LayoutElementReference { typedef Iterator<CLayoutElementReference> iterator; };
	MemberElement<CLayoutLengthUnitType, _altova_mi_altova_CCMSD_altova_LayoutLengthUnit> LayoutLengthUnit;
	struct LayoutLengthUnit { typedef Iterator<CLayoutLengthUnitType> iterator; };
	MemberElement<CLayoutObject, _altova_mi_altova_CCMSD_altova_LayoutObject> LayoutObject;
	struct LayoutObject { typedef Iterator<CLayoutObject> iterator; };
	MemberElement<CLengthType, _altova_mi_altova_CCMSD_altova_LengthType> LengthType;
	struct LengthType { typedef Iterator<CLengthType> iterator; };
	MemberElement<CLengthUnitType, _altova_mi_altova_CCMSD_altova_LengthUnit> LengthUnit;
	struct LengthUnit { typedef Iterator<CLengthUnitType> iterator; };
	MemberElement<CLimitedUniqueEntity, _altova_mi_altova_CCMSD_altova_LimitedUniqueEntity> LimitedUniqueEntity;
	struct LimitedUniqueEntity { typedef Iterator<CLimitedUniqueEntity> iterator; };
	MemberElement<CLocationDefinition, _altova_mi_altova_CCMSD_altova_LocationDefinition> LocationDefinition;
	struct LocationDefinition { typedef Iterator<CLocationDefinition> iterator; };
	MemberElement<CLotInformation, _altova_mi_altova_CCMSD_altova_LotInformation> LotInformation;
	struct LotInformation { typedef Iterator<CLotInformation> iterator; };
	MemberElement<CMachineProgramData, _altova_mi_altova_CCMSD_altova_MachineProgramData> MachineProgramData;
	struct MachineProgramData { typedef Iterator<CMachineProgramData> iterator; };
	MemberElement<CMaintenancePlan, _altova_mi_altova_CCMSD_altova_MaintenancePlan> MaintenancePlan;
	struct MaintenancePlan { typedef Iterator<CMaintenancePlan> iterator; };
	MemberElement<CMaintenancePlanReference, _altova_mi_altova_CCMSD_altova_MaintenancePlanReference> MaintenancePlanReference;
	struct MaintenancePlanReference { typedef Iterator<CMaintenancePlanReference> iterator; };
	MemberElement<CMaintenanceProcess, _altova_mi_altova_CCMSD_altova_MaintenanceProcess> MaintenanceProcess;
	struct MaintenanceProcess { typedef Iterator<CMaintenanceProcess> iterator; };
	MemberElement<CMaintenanceProcessConstraint, _altova_mi_altova_CCMSD_altova_MaintenanceProcessConstraint> MaintenanceProcessConstraint;
	struct MaintenanceProcessConstraint { typedef Iterator<CMaintenanceProcessConstraint> iterator; };
	MemberElement<CMaintenanceProcessGroup, _altova_mi_altova_CCMSD_altova_MaintenanceProcessGroup> MaintenanceProcessGroup;
	struct MaintenanceProcessGroup { typedef Iterator<CMaintenanceProcessGroup> iterator; };
	MemberElement<CMaintenanceProcessReference, _altova_mi_altova_CCMSD_altova_MaintenanceProcessReference> MaintenanceProcessReference;
	struct MaintenanceProcessReference { typedef Iterator<CMaintenanceProcessReference> iterator; };
	MemberElement<CMetadata, _altova_mi_altova_CCMSD_altova_Metadata> Metadata;
	struct Metadata { typedef Iterator<CMetadata> iterator; };
	MemberElement<CMultiSchemaCMSDValidator, _altova_mi_altova_CCMSD_altova_MultiSchemaCMSDValidator> MultiSchemaCMSDValidator;
	struct MultiSchemaCMSDValidator { typedef Iterator<CMultiSchemaCMSDValidator> iterator; };
	MemberElement<CNewSetup, _altova_mi_altova_CCMSD_altova_NewSetup> NewSetup;
	struct NewSetup { typedef Iterator<CNewSetup> iterator; };
	MemberElement<CNonNegativeIntegerType, _altova_mi_altova_CCMSD_altova_NonNegativeInteger> NonNegativeInteger;
	struct NonNegativeInteger { typedef Iterator<CNonNegativeIntegerType> iterator; };
	MemberElement<CNotifyPropertyChangeBase, _altova_mi_altova_CCMSD_altova_NotifyPropertyChangeBase> NotifyPropertyChangeBase;
	struct NotifyPropertyChangeBase { typedef Iterator<CNotifyPropertyChangeBase> iterator; };
	MemberElement<COrder, _altova_mi_altova_CCMSD_altova_Order> Order;
	struct Order { typedef Iterator<COrder> iterator; };
	MemberElement<COrderInformationReference, _altova_mi_altova_CCMSD_altova_OrderInformationReference> OrderInformationReference;
	struct OrderInformationReference { typedef Iterator<COrderInformationReference> iterator; };
	MemberElement<COrderLine, _altova_mi_altova_CCMSD_altova_OrderLine> OrderLine;
	struct OrderLine { typedef Iterator<COrderLine> iterator; };
	MemberElement<COrderLinePartDescription, _altova_mi_altova_CCMSD_altova_OrderLinePartDescription> OrderLinePartDescription;
	struct OrderLinePartDescription { typedef Iterator<COrderLinePartDescription> iterator; };
	MemberElement<COrderLineServiceDescription, _altova_mi_altova_CCMSD_altova_OrderLineServiceDescription> OrderLineServiceDescription;
	struct OrderLineServiceDescription { typedef Iterator<COrderLineServiceDescription> iterator; };
	MemberElement<COrderStatusType, _altova_mi_altova_CCMSD_altova_OrderStatus> OrderStatus;
	struct OrderStatus { typedef Iterator<COrderStatusType> iterator; };
	MemberElement<CPart, _altova_mi_altova_CCMSD_altova_Part> Part;
	struct Part { typedef Iterator<CPart> iterator; };
	MemberElement<CPartGroup, _altova_mi_altova_CCMSD_altova_PartGroup> PartGroup;
	struct PartGroup { typedef Iterator<CPartGroup> iterator; };
	MemberElement<CPartProductionStatusType, _altova_mi_altova_CCMSD_altova_PartProductionStatus> PartProductionStatus;
	struct PartProductionStatus { typedef Iterator<CPartProductionStatusType> iterator; };
	MemberElement<CPartReference, _altova_mi_altova_CCMSD_altova_PartReference> PartReference;
	struct PartReference { typedef Iterator<CPartReference> iterator; };
	MemberElement<CPartType, _altova_mi_altova_CCMSD_altova_PartType> PartType;
	struct PartType { typedef Iterator<CPartType> iterator; };
	MemberElement<CPartTypeReference, _altova_mi_altova_CCMSD_altova_PartTypeReference> PartTypeReference;
	struct PartTypeReference { typedef Iterator<CPartTypeReference> iterator; };
	MemberElement<CPerMeasuredAmountPackaging, _altova_mi_altova_CCMSD_altova_PerMeasuredAmountPackaging> PerMeasuredAmountPackaging;
	struct PerMeasuredAmountPackaging { typedef Iterator<CPerMeasuredAmountPackaging> iterator; };
	MemberElement<CPerPiecePackaging, _altova_mi_altova_CCMSD_altova_PerPiecePackaging> PerPiecePackaging;
	struct PerPiecePackaging { typedef Iterator<CPerPiecePackaging> iterator; };
	MemberElement<CPhone, _altova_mi_altova_CCMSD_altova_Phone> Phone;
	struct Phone { typedef Iterator<CPhone> iterator; };
	MemberElement<CPlacement, _altova_mi_altova_CCMSD_altova_Placement> Placement;
	struct Placement { typedef Iterator<CPlacement> iterator; };
	MemberElement<CPowerType, _altova_mi_altova_CCMSD_altova_PowerType> PowerType;
	struct PowerType { typedef Iterator<CPowerType> iterator; };
	MemberElement<CPowerUnitType, _altova_mi_altova_CCMSD_altova_PowerUnit> PowerUnit;
	struct PowerUnit { typedef Iterator<CPowerUnitType> iterator; };
	MemberElement<CPrecedenceConstraint, _altova_mi_altova_CCMSD_altova_PrecedenceConstraint> PrecedenceConstraint;
	struct PrecedenceConstraint { typedef Iterator<CPrecedenceConstraint> iterator; };
	MemberElement<CPrecedenceRelationshipType, _altova_mi_altova_CCMSD_altova_PrecedenceRelationship> PrecedenceRelationship;
	struct PrecedenceRelationship { typedef Iterator<CPrecedenceRelationshipType> iterator; };
	MemberElement<CProcess, _altova_mi_altova_CCMSD_altova_Process> Process;
	struct Process { typedef Iterator<CProcess> iterator; };
	MemberElement<CProcessConstraint, _altova_mi_altova_CCMSD_altova_ProcessConstraint> ProcessConstraint;
	struct ProcessConstraint { typedef Iterator<CProcessConstraint> iterator; };
	MemberElement<CProcessGroup, _altova_mi_altova_CCMSD_altova_ProcessGroup> ProcessGroup;
	struct ProcessGroup { typedef Iterator<CProcessGroup> iterator; };
	MemberElement<CProcessGroupTypeType, _altova_mi_altova_CCMSD_altova_ProcessGroupType> ProcessGroupType;
	struct ProcessGroupType { typedef Iterator<CProcessGroupTypeType> iterator; };
	MemberElement<CProcessPlan, _altova_mi_altova_CCMSD_altova_ProcessPlan> ProcessPlan;
	struct ProcessPlan { typedef Iterator<CProcessPlan> iterator; };
	MemberElement<CProcessPlanReference, _altova_mi_altova_CCMSD_altova_ProcessPlanReference> ProcessPlanReference;
	struct ProcessPlanReference { typedef Iterator<CProcessPlanReference> iterator; };
	MemberElement<CProcessReference, _altova_mi_altova_CCMSD_altova_ProcessReference> ProcessReference;
	struct ProcessReference { typedef Iterator<CProcessReference> iterator; };
	MemberElement<CProperty, _altova_mi_altova_CCMSD_altova_Property> Property;
	struct Property { typedef Iterator<CProperty> iterator; };
	MemberElement<CPropertyCardinality, _altova_mi_altova_CCMSD_altova_PropertyCardinality> PropertyCardinality;
	struct PropertyCardinality { typedef Iterator<CPropertyCardinality> iterator; };
	MemberElement<CPropertyDataTypeDescription, _altova_mi_altova_CCMSD_altova_PropertyDataTypeDescription> PropertyDataTypeDescription;
	struct PropertyDataTypeDescription { typedef Iterator<CPropertyDataTypeDescription> iterator; };
	MemberElement<CPropertyDescription, _altova_mi_altova_CCMSD_altova_PropertyDescription> PropertyDescription;
	struct PropertyDescription { typedef Iterator<CPropertyDescription> iterator; };
	MemberElement<CPropertyDescriptionReference, _altova_mi_altova_CCMSD_altova_PropertyDescriptionReference> PropertyDescriptionReference;
	struct PropertyDescriptionReference { typedef Iterator<CPropertyDescriptionReference> iterator; };
	MemberElement<CPropertyExtensibleEntityType, _altova_mi_altova_CCMSD_altova_PropertyExtensibleEntity> PropertyExtensibleEntity;
	struct PropertyExtensibleEntity { typedef Iterator<CPropertyExtensibleEntityType> iterator; };
	MemberElement<CPropertyTypeType, _altova_mi_altova_CCMSD_altova_PropertyType> PropertyType;
	struct PropertyType { typedef Iterator<CPropertyTypeType> iterator; };
	MemberElement<CQuantityType, _altova_mi_altova_CCMSD_altova_QuantityType> QuantityType;
	struct QuantityType { typedef Iterator<CQuantityType> iterator; };
	MemberElement<CReferenceMaterial, _altova_mi_altova_CCMSD_altova_ReferenceMaterial> ReferenceMaterial;
	struct ReferenceMaterial { typedef Iterator<CReferenceMaterial> iterator; };
	MemberElement<CReferenceMaterialReference, _altova_mi_altova_CCMSD_altova_ReferenceMaterialReference> ReferenceMaterialReference;
	struct ReferenceMaterialReference { typedef Iterator<CReferenceMaterialReference> iterator; };
	MemberElement<CReferenceProperty, _altova_mi_altova_CCMSD_altova_ReferenceProperty> ReferenceProperty;
	struct ReferenceProperty { typedef Iterator<CReferenceProperty> iterator; };
	MemberElement<CReferenceTypeNameType, _altova_mi_altova_CCMSD_altova_ReferenceTypeName> ReferenceTypeName;
	struct ReferenceTypeName { typedef Iterator<CReferenceTypeNameType> iterator; };
	MemberElement<CReferencingEntity, _altova_mi_altova_CCMSD_altova_ReferencingEntity> ReferencingEntity;
	struct ReferencingEntity { typedef Iterator<CReferencingEntity> iterator; };
	MemberElement<CRelaxNGCMSDValidator, _altova_mi_altova_CCMSD_altova_RelaxNGCMSDValidator> RelaxNGCMSDValidator;
	struct RelaxNGCMSDValidator { typedef Iterator<CRelaxNGCMSDValidator> iterator; };
	MemberElement<CRelaxNGCMSDValidatorWithCache, _altova_mi_altova_CCMSD_altova_RelaxNGCMSDValidatorWithCache> RelaxNGCMSDValidatorWithCache;
	struct RelaxNGCMSDValidatorWithCache { typedef Iterator<CRelaxNGCMSDValidatorWithCache> iterator; };
	MemberElement<CRequiredApplication, _altova_mi_altova_CCMSD_altova_RequiredApplication> RequiredApplication;
	struct RequiredApplication { typedef Iterator<CRequiredApplication> iterator; };
	MemberElement<CResource, _altova_mi_altova_CCMSD_altova_Resource> Resource;
	struct Resource { typedef Iterator<CResource> iterator; };
	MemberElement<CResourceClass, _altova_mi_altova_CCMSD_altova_ResourceClass> ResourceClass;
	struct ResourceClass { typedef Iterator<CResourceClass> iterator; };
	MemberElement<CResourceClassReference, _altova_mi_altova_CCMSD_altova_ResourceClassReference> ResourceClassReference;
	struct ResourceClassReference { typedef Iterator<CResourceClassReference> iterator; };
	MemberElement<CResourceGroupInformation, _altova_mi_altova_CCMSD_altova_ResourceGroupInformation> ResourceGroupInformation;
	struct ResourceGroupInformation { typedef Iterator<CResourceGroupInformation> iterator; };
	MemberElement<CResourceGroupMember, _altova_mi_altova_CCMSD_altova_ResourceGroupMember> ResourceGroupMember;
	struct ResourceGroupMember { typedef Iterator<CResourceGroupMember> iterator; };
	MemberElement<CResourceReference, _altova_mi_altova_CCMSD_altova_ResourceReference> ResourceReference;
	struct ResourceReference { typedef Iterator<CResourceReference> iterator; };
	MemberElement<CResourceStatusType, _altova_mi_altova_CCMSD_altova_ResourceStatus> ResourceStatus;
	struct ResourceStatus { typedef Iterator<CResourceStatusType> iterator; };
	MemberElement<CResourceTypeType, _altova_mi_altova_CCMSD_altova_ResourceType> ResourceType;
	struct ResourceType { typedef Iterator<CResourceTypeType> iterator; };
	MemberElement<CResourcesRequired, _altova_mi_altova_CCMSD_altova_ResourcesRequired> ResourcesRequired;
	struct ResourcesRequired { typedef Iterator<CResourcesRequired> iterator; };
	MemberElement<CRotation, _altova_mi_altova_CCMSD_altova_Rotation> Rotation;
	struct Rotation { typedef Iterator<CRotation> iterator; };
	MemberElement<CScaling, _altova_mi_altova_CCMSD_altova_Scaling> Scaling;
	struct Scaling { typedef Iterator<CScaling> iterator; };
	MemberElement<CSchedule, _altova_mi_altova_CCMSD_altova_Schedule> Schedule;
	struct Schedule { typedef Iterator<CSchedule> iterator; };
	MemberElement<CScheduleInformationReference, _altova_mi_altova_CCMSD_altova_ScheduleInformationReference> ScheduleInformationReference;
	struct ScheduleInformationReference { typedef Iterator<CScheduleInformationReference> iterator; };
	MemberElement<CScheduleItem, _altova_mi_altova_CCMSD_altova_ScheduleItem> ScheduleItem;
	struct ScheduleItem { typedef Iterator<CScheduleItem> iterator; };
	MemberElement<CScheduleItemEffortDescription, _altova_mi_altova_CCMSD_altova_ScheduleItemEffortDescription> ScheduleItemEffortDescription;
	struct ScheduleItemEffortDescription { typedef Iterator<CScheduleItemEffortDescription> iterator; };
	MemberElement<CSegmentShape, _altova_mi_altova_CCMSD_altova_SegmentShape> SegmentShape;
	struct SegmentShape { typedef Iterator<CSegmentShape> iterator; };
	MemberElement<CSegmentTypeType, _altova_mi_altova_CCMSD_altova_SegmentType> SegmentType;
	struct SegmentType { typedef Iterator<CSegmentTypeType> iterator; };
	MemberElement<CSetupChangeoverDefinition, _altova_mi_altova_CCMSD_altova_SetupChangeoverDefinition> SetupChangeoverDefinition;
	struct SetupChangeoverDefinition { typedef Iterator<CSetupChangeoverDefinition> iterator; };
	MemberElement<CSetupChangeoverReference, _altova_mi_altova_CCMSD_altova_SetupChangeoverReference> SetupChangeoverReference;
	struct SetupChangeoverReference { typedef Iterator<CSetupChangeoverReference> iterator; };
	MemberElement<CSetupDefinition, _altova_mi_altova_CCMSD_altova_SetupDefinition> SetupDefinition;
	struct SetupDefinition { typedef Iterator<CSetupDefinition> iterator; };
	MemberElement<CSetupDefinitionReference, _altova_mi_altova_CCMSD_altova_SetupDefinitionReference> SetupDefinitionReference;
	struct SetupDefinitionReference { typedef Iterator<CSetupDefinitionReference> iterator; };
	MemberElement<CShapeDescription, _altova_mi_altova_CCMSD_altova_ShapeDescription> ShapeDescription;
	struct ShapeDescription { typedef Iterator<CShapeDescription> iterator; };
	MemberElement<CShapeDescriptionTypeType, _altova_mi_altova_CCMSD_altova_ShapeDescriptionType> ShapeDescriptionType;
	struct ShapeDescriptionType { typedef Iterator<CShapeDescriptionTypeType> iterator; };
	MemberElement<CShapeLabelDefinition, _altova_mi_altova_CCMSD_altova_ShapeLabelDefinition> ShapeLabelDefinition;
	struct ShapeLabelDefinition { typedef Iterator<CShapeLabelDefinition> iterator; };
	MemberElement<CShift, _altova_mi_altova_CCMSD_altova_Shift> Shift;
	struct Shift { typedef Iterator<CShift> iterator; };
	MemberElement<CShiftSchedule, _altova_mi_altova_CCMSD_altova_ShiftSchedule> ShiftSchedule;
	struct ShiftSchedule { typedef Iterator<CShiftSchedule> iterator; };
	MemberElement<CSimpleDataTypeNameType, _altova_mi_altova_CCMSD_altova_SimpleDataTypeName> SimpleDataTypeName;
	struct SimpleDataTypeName { typedef Iterator<CSimpleDataTypeNameType> iterator; };
	MemberElement<CSimpleProperty, _altova_mi_altova_CCMSD_altova_SimpleProperty> SimpleProperty;
	struct SimpleProperty { typedef Iterator<CSimpleProperty> iterator; };
	MemberElement<CSkillDefinition, _altova_mi_altova_CCMSD_altova_SkillDefinition> SkillDefinition;
	struct SkillDefinition { typedef Iterator<CSkillDefinition> iterator; };
	MemberElement<CSkillLevel, _altova_mi_altova_CCMSD_altova_SkillLevel> SkillLevel;
	struct SkillLevel { typedef Iterator<CSkillLevel> iterator; };
	MemberElement<CSkillReference, _altova_mi_altova_CCMSD_altova_SkillReference> SkillReference;
	struct SkillReference { typedef Iterator<CSkillReference> iterator; };
	MemberElement<CSpatialDimension, _altova_mi_altova_CCMSD_altova_SpatialDimension> SpatialDimension;
	struct SpatialDimension { typedef Iterator<CSpatialDimension> iterator; };
	MemberElement<CSpeedType, _altova_mi_altova_CCMSD_altova_SpeedType> SpeedType;
	struct SpeedType { typedef Iterator<CSpeedType> iterator; };
	MemberElement<CSpeedUnitType, _altova_mi_altova_CCMSD_altova_SpeedUnit> SpeedUnit;
	struct SpeedUnit { typedef Iterator<CSpeedUnitType> iterator; };
	MemberElement<CStochasticProperty, _altova_mi_altova_CCMSD_altova_StochasticProperty> StochasticProperty;
	struct StochasticProperty { typedef Iterator<CStochasticProperty> iterator; };
	MemberElement<CTemperatureType, _altova_mi_altova_CCMSD_altova_TemperatureType> TemperatureType;
	struct TemperatureType { typedef Iterator<CTemperatureType> iterator; };
	MemberElement<CTemperatureUnitType, _altova_mi_altova_CCMSD_altova_TemperatureUnit> TemperatureUnit;
	struct TemperatureUnit { typedef Iterator<CTemperatureUnitType> iterator; };
	MemberElement<CTextAnchorLocationType, _altova_mi_altova_CCMSD_altova_TextAnchorLocation> TextAnchorLocation;
	struct TextAnchorLocation { typedef Iterator<CTextAnchorLocationType> iterator; };
	MemberElement<CTextualAnnotation, _altova_mi_altova_CCMSD_altova_TextualAnnotation> TextualAnnotation;
	struct TextualAnnotation { typedef Iterator<CTextualAnnotation> iterator; };
	MemberElement<CTimeType, _altova_mi_altova_CCMSD_altova_Time> Time;
	struct Time { typedef Iterator<CTimeType> iterator; };
	MemberElement<CTimeUnitType, _altova_mi_altova_CCMSD_altova_TimeUnit> TimeUnit;
	struct TimeUnit { typedef Iterator<CTimeUnitType> iterator; };
	MemberElement<CTimestampType, _altova_mi_altova_CCMSD_altova_Timestamp> Timestamp;
	struct Timestamp { typedef Iterator<CTimestampType> iterator; };
	MemberElement<CTransformationOperation, _altova_mi_altova_CCMSD_altova_TransformationOperation> TransformationOperation;
	struct TransformationOperation { typedef Iterator<CTransformationOperation> iterator; };
	MemberElement<CTranslation, _altova_mi_altova_CCMSD_altova_Translation> Translation;
	struct Translation { typedef Iterator<CTranslation> iterator; };
	MemberElement<CURIType, _altova_mi_altova_CCMSD_altova_URI> URI;
	struct URI { typedef Iterator<CURIType> iterator; };
	MemberElement<CUniqueEntity, _altova_mi_altova_CCMSD_altova_UniqueEntity> UniqueEntity;
	struct UniqueEntity { typedef Iterator<CUniqueEntity> iterator; };
	MemberElement<CUniqueEntityTypeType, _altova_mi_altova_CCMSD_altova_UniqueEntityType> UniqueEntityType;
	struct UniqueEntityType { typedef Iterator<CUniqueEntityTypeType> iterator; };
	MemberElement<CUnitDefaults, _altova_mi_altova_CCMSD_altova_UnitDefaults> UnitDefaults;
	struct UnitDefaults { typedef Iterator<CUnitDefaults> iterator; };
	MemberElement<CUnitTypeNameType, _altova_mi_altova_CCMSD_altova_UnitTypeName> UnitTypeName;
	struct UnitTypeName { typedef Iterator<CUnitTypeNameType> iterator; };
	MemberElement<CValidationResult, _altova_mi_altova_CCMSD_altova_ValidationResult> ValidationResult;
	struct ValidationResult { typedef Iterator<CValidationResult> iterator; };
	MemberElement<CVariableCostData, _altova_mi_altova_CCMSD_altova_VariableCostData> VariableCostData;
	struct VariableCostData { typedef Iterator<CVariableCostData> iterator; };
	MemberElement<CVolumeType, _altova_mi_altova_CCMSD_altova_VolumeType> VolumeType;
	struct VolumeType { typedef Iterator<CVolumeType> iterator; };
	MemberElement<CVolumeUnitType, _altova_mi_altova_CCMSD_altova_VolumeUnit> VolumeUnit;
	struct VolumeUnit { typedef Iterator<CVolumeUnitType> iterator; };
	MemberElement<CWeightType, _altova_mi_altova_CCMSD_altova_WeightType> WeightType;
	struct WeightType { typedef Iterator<CWeightType> iterator; };
	MemberElement<CWeightUnitType, _altova_mi_altova_CCMSD_altova_WeightUnit> WeightUnit;
	struct WeightUnit { typedef Iterator<CWeightUnitType> iterator; };
	MemberElement<CXSDCMSDValidator, _altova_mi_altova_CCMSD_altova_XSDCMSDValidator> XSDCMSDValidator;
	struct XSDCMSDValidator { typedef Iterator<CXSDCMSDValidator> iterator; };
	MemberElement<xs::Call, _altova_mi_altova_CCMSD_altova_all> all;
	struct all { typedef Iterator<xs::Call> iterator; };
	MemberElement<CannotationType, _altova_mi_altova_CCMSD_altova_annotation> annotation;
	struct annotation { typedef Iterator<CannotationType> iterator; };
	MemberElement<CanyType, _altova_mi_altova_CCMSD_altova_any> any;
	struct any { typedef Iterator<CanyType> iterator; };
	MemberElement<xs::Cwildcard, _altova_mi_altova_CCMSD_altova_anyAttribute> anyAttribute;
	struct anyAttribute { typedef Iterator<xs::Cwildcard> iterator; };
	MemberElement<CappinfoType, _altova_mi_altova_CCMSD_altova_appinfo> appinfo;
	struct appinfo { typedef Iterator<CappinfoType> iterator; };
	MemberElement<xs::CtopLevelAttribute, _altova_mi_altova_CCMSD_altova_attribute> attribute;
	struct attribute { typedef Iterator<xs::CtopLevelAttribute> iterator; };
	MemberElement<xs::CnamedAttributeGroup, _altova_mi_altova_CCMSD_altova_attributeGroup> attributeGroup;
	struct attributeGroup { typedef Iterator<xs::CnamedAttributeGroup> iterator; };
	MemberElement<xs::CexplicitGroup, _altova_mi_altova_CCMSD_altova_choice> choice;
	struct choice { typedef Iterator<xs::CexplicitGroup> iterator; };
	MemberElement<CcomplexContentType, _altova_mi_altova_CCMSD_altova_complexContent> complexContent;
	struct complexContent { typedef Iterator<CcomplexContentType> iterator; };
	MemberElement<xs::CtopLevelComplexType, _altova_mi_altova_CCMSD_altova_complexType> complexType;
	struct complexType { typedef Iterator<xs::CtopLevelComplexType> iterator; };
	MemberElement<CdocumentationType, _altova_mi_altova_CCMSD_altova_documentation> documentation;
	struct documentation { typedef Iterator<CdocumentationType> iterator; };
	MemberElement<xs::CtopLevelElement, _altova_mi_altova_CCMSD_altova_element> element;
	struct element { typedef Iterator<xs::CtopLevelElement> iterator; };
	MemberElement<xs::CnoFixedFacet, _altova_mi_altova_CCMSD_altova_enumeration> enumeration;
	struct enumeration { typedef Iterator<xs::CnoFixedFacet> iterator; };
	MemberElement<CfieldType, _altova_mi_altova_CCMSD_altova_field> field;
	struct field { typedef Iterator<CfieldType> iterator; };
	MemberElement<xs::CnumFacet, _altova_mi_altova_CCMSD_altova_fractionDigits> fractionDigits;
	struct fractionDigits { typedef Iterator<xs::CnumFacet> iterator; };
	MemberElement<xs::CnamedGroup, _altova_mi_altova_CCMSD_altova_group> group;
	struct group { typedef Iterator<xs::CnamedGroup> iterator; };
	MemberElement<CimportType, _altova_mi_altova_CCMSD_altova_import> import;
	struct import { typedef Iterator<CimportType> iterator; };
	MemberElement<CincludeType, _altova_mi_altova_CCMSD_altova_include> include;
	struct include { typedef Iterator<CincludeType> iterator; };
	MemberElement<xs::Ckeybase, _altova_mi_altova_CCMSD_altova_key> key;
	struct key { typedef Iterator<xs::Ckeybase> iterator; };
	MemberElement<CkeyrefType, _altova_mi_altova_CCMSD_altova_keyref> keyref;
	struct keyref { typedef Iterator<CkeyrefType> iterator; };
	MemberElement<xs::CnumFacet, _altova_mi_altova_CCMSD_altova_length> length;
	struct length { typedef Iterator<xs::CnumFacet> iterator; };
	MemberElement<ClistType, _altova_mi_altova_CCMSD_altova_list> list;
	struct list { typedef Iterator<ClistType> iterator; };
	MemberElement<xs::Cfacet, _altova_mi_altova_CCMSD_altova_maxExclusive> maxExclusive;
	struct maxExclusive { typedef Iterator<xs::Cfacet> iterator; };
	MemberElement<xs::Cfacet, _altova_mi_altova_CCMSD_altova_maxInclusive> maxInclusive;
	struct maxInclusive { typedef Iterator<xs::Cfacet> iterator; };
	MemberElement<xs::CnumFacet, _altova_mi_altova_CCMSD_altova_maxLength> maxLength;
	struct maxLength { typedef Iterator<xs::CnumFacet> iterator; };
	MemberElement<xs::Cfacet, _altova_mi_altova_CCMSD_altova_minExclusive> minExclusive;
	struct minExclusive { typedef Iterator<xs::Cfacet> iterator; };
	MemberElement<xs::Cfacet, _altova_mi_altova_CCMSD_altova_minInclusive> minInclusive;
	struct minInclusive { typedef Iterator<xs::Cfacet> iterator; };
	MemberElement<xs::CnumFacet, _altova_mi_altova_CCMSD_altova_minLength> minLength;
	struct minLength { typedef Iterator<xs::CnumFacet> iterator; };
	MemberElement<CnotationType, _altova_mi_altova_CCMSD_altova_notation> notation;
	struct notation { typedef Iterator<CnotationType> iterator; };
	MemberElement<CpatternType, _altova_mi_altova_CCMSD_altova_pattern> pattern;
	struct pattern { typedef Iterator<CpatternType> iterator; };
	MemberElement<CredefineType, _altova_mi_altova_CCMSD_altova_redefine> redefine;
	struct redefine { typedef Iterator<CredefineType> iterator; };
	MemberElement<CrestrictionType, _altova_mi_altova_CCMSD_altova_restriction> restriction;
	struct restriction { typedef Iterator<CrestrictionType> iterator; };
	MemberElement<CschemaType, _altova_mi_altova_CCMSD_altova_schema> schema;
	struct schema { typedef Iterator<CschemaType> iterator; };
	MemberElement<xs::CselectorType, _altova_mi_altova_CCMSD_altova_selector> selector;
	struct selector { typedef Iterator<xs::CselectorType> iterator; };
	MemberElement<xs::CexplicitGroup, _altova_mi_altova_CCMSD_altova_sequence> sequence;
	struct sequence { typedef Iterator<xs::CexplicitGroup> iterator; };
	MemberElement<CsimpleContentType, _altova_mi_altova_CCMSD_altova_simpleContent> simpleContent;
	struct simpleContent { typedef Iterator<CsimpleContentType> iterator; };
	MemberElement<xs::CtopLevelSimpleType, _altova_mi_altova_CCMSD_altova_simpleType> simpleType;
	struct simpleType { typedef Iterator<xs::CtopLevelSimpleType> iterator; };
	MemberElement<CtotalDigitsType, _altova_mi_altova_CCMSD_altova_totalDigits> totalDigits;
	struct totalDigits { typedef Iterator<CtotalDigitsType> iterator; };
	MemberElement<CunionType, _altova_mi_altova_CCMSD_altova_union2> union2;
	struct union2 { typedef Iterator<CunionType> iterator; };
	MemberElement<xs::Ckeybase, _altova_mi_altova_CCMSD_altova_unique> unique;
	struct unique { typedef Iterator<xs::Ckeybase> iterator; };
	MemberElement<CwhiteSpaceType, _altova_mi_altova_CCMSD_altova_whiteSpace> whiteSpace;
	struct whiteSpace { typedef Iterator<CwhiteSpaceType> iterator; };
	CMSD_EXPORT void SetXsiType();

	// document functions
	CMSD_EXPORT static CCMSD LoadFromFile(const string_type& fileName);
	CMSD_EXPORT static CCMSD LoadFromString(const string_type& xml);
	CMSD_EXPORT static CCMSD LoadFromBinary(const std::vector<unsigned char>& data);
	CMSD_EXPORT void SaveToFile( const string_type& fileName, bool prettyPrint );
	CMSD_EXPORT void SaveToFile( const string_type& fileName, bool prettyPrint, const string_type& encoding );
	CMSD_EXPORT void SaveToFile( const string_type& fileName, bool prettyPrint, const string_type& encoding, bool bBigEndian, bool bBOM );
	CMSD_EXPORT string_type SaveToString(bool prettyPrint);
	CMSD_EXPORT std::vector<unsigned char> SaveToBinary(bool prettyPrint);
	CMSD_EXPORT std::vector<unsigned char> SaveToBinary(bool prettyPrint, const string_type& encoding);
	CMSD_EXPORT std::vector<unsigned char> SaveToBinary(bool prettyPrint, const string_type& encoding, bool bBigEndian, bool bBOM);
 	CMSD_EXPORT static CCMSD CreateDocument();
	CMSD_EXPORT void DestroyDocument();
	CMSD_EXPORT void SetDTDLocation(const string_type& dtdLocation);
	CMSD_EXPORT void SetSchemaLocation(const string_type& schemaLocation);
protected:
	MsxmlTreeOperations::DocumentType GetDocumentNode() { return (MsxmlTreeOperations::DocumentType)m_node; }
};


}	// namespace CMSD

#endif // _ALTOVA_INCLUDED_CMSD_ALTOVA__ALTOVA_CCMSD
