////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#pragma once
#ifndef ALTOVA_STDAFX_H_INCLUDED
#define ALTOVA_STDAFX_H_INCLUDED

#if _MSC_VER < 1300
#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information
#endif

#if !defined( __GNUC__ )

#include <tchar.h>
#include <windows.h>

#endif


//#import "msxml6.dll" named_guids no_implementation




//{{AFX_INSERT_LOCATION}}

#endif // ALTOVA_STDAFX_H_INCLUDED
